export const MsgID = {
    BOOT_UP: 1,
    OUT_OF_SERVICE_MISSING_DATA: 2,
    OUT_OF_SERVICE_INFO: 3,
    SHUTTING_DOWN: 4,
    DAGW_OPERATION: 5,
    TRIGGER_DAGW_OPERATION: 6,
    TRIGGER_BOLC_STATUS: 7,
    CHANGE_BOLC_STATUS: 8,
    SD_FOR_UPGRADING: 9,
    SD_FOR_UPGRADING_FROM_TO: 10,

    START_TRIP: 12,
    START_TRIP_GET_SERVICE_LIST: 13,
    START_TRIP_GET_FARE_TRIP_DETAILS: 14,
    START_TRIP_BUS_STOP_LIST: 15,
    START_TRIP_SUBMIT_FARE_TRIP: 16,
    START_TRIP_SUBMIT_SERVICE: 17,
    START_TRIP_POP_UP_MESSAGE: 18,
    START_TRIP_CANCEL_FLOW: 11,
    START_TRIP_SELECT_FARE_DETAIL_BTN: 53,
    START_TRIP_INFORMATION_FOR_SPECIAL_CASE: 54,

    MAIN_ACCESS_DENIED: 99,
    BUS_OPERATION_MENU: 100,

    END_SHIFT: 19,

    BC_TAP_CARD_LOGIN: 20,
    BC_TAP_CARD_PIN: 21,
    BC_TAP_CARD_DUTY: 22,

    MANUAL_LOGIN: 24,
    MANUAL_LOGIN_PIN: 25,
    MANUAL_LOGIN_STAFF_ID: 26,
    MANUAL_LOGIN_DUTY: 27,
    MANUAL_LOGIN_PIN2: 28,

    MS_TAP_CARD_LOGIN: 40,
    MS_TAP_CARD_PIN: 41,

    END_TRIP: 29,
    END_TRIP_TYPE: 30,
    END_TRIP_CANCEL: 31,
    END_TRIP_SUBMIT: 32,
    END_TRIP_SUBMIT_CANCEL: 33,

    FARE_CONSOLE: 80,
    DECK_TYPE_LIST: 81,
    DECK_TYPE_SUBMIT: 82,
    BLS_STATUS_SUBMIT: 83,
    TIME_SUBMIT: 84,
    DATE_SUBMIT: 85,
    COMPLIMENTARY_DAYS_SUBMIT: 86,
    DELETE_PARAMETER: 87,
    FARE_CONSOLE_SUBMIT: 88,
    DELETE_PARAMETER_NOTIFY: 89,
    COMMISSION_BUS_ID: 90,
    COMMISSION_OPERATOR: 91,
    COMMISSION_BUS_ID_SUBMIT: 92,
    // COMMISSION_BUS_ID_CHANGE: 95,
    // COMMISSION_OPERATOR_CHANGE: 96,
    // COMMISSION_SPID_CHANGE: 97,

    MAIN_PAGE_DATA: 101,
    CV_STATUS: 102,
    CV_ICONS: 103,
    UPDATE_FARE_BUS_STOP: 104,
    UPDATE_FMS_BUS_STOP: 105,
    UPDATE_HEADWAY: 106,
    UPDATE_FARE_BUS_STOP_LIST: 107,
    MAIN_UP_DOWN_BTN: 108,
    MAIN_UPDATE_FARE_BUS_STOP: 109,
    NEXT_BUS_INFO: 118,

    BOOT_UP_COMMISSIONING: 150,
    DECOMMISSION: 151,

    TIMEOUT_MESSAGE: 110,

    EXTERNAL_DEVICES: 111,
    EXTERNAL_DEVICES_NOTIFY: 112,
    EXT_DEVICE_SUBMIT: 113,
    EXT_DEVICE_CANCEL: 114,

    LOGOUT: 115,

    LANGUAGE: 116,
    LANGUAGE_SUBMIT: 117,
    LANGUAGE_NOTIFY: 119,

    // main button
    MAIN_BUTTON: 140,
    // MAIN SCREEN
    MAIN_FREE: 500,
    MAIN_REAR_DOORS: 501,
    MAIN_BREAKDOWN: 502,
    MAIN_FRONT_DOOR: 503,
    MAIN_REDEEM: 504,
    MAIN_CASH: 505,

    MAIN_FREE_SUBMIT: 141,
    MAIN_FREE_CANCEL: 142,

    // MAIN_REAR_DOORS: 142,
    MAIN_REAR_DOORS_SUBMIT: 143,

    BREAKDOWN_BUS_STOP_LIST: 157,
    BREAKDOWN_CHANGE_BUS_STOP: 158,
    BREAKDOWN_SUBMIT: 159,
    BREAKDOWN_SUBMIT_REASON: 160,
    BREAKDOWN_SUBMIT_COMP_TICKET: 161,
    BREAKDOWN_PROCESS_COMP_TICKET: 162,
    BREAKDOWN_SUBMIT_BREAKDOWN_TICKET: 163,
    BREAKDOWN_PROCESS_BREAKDOWN_TICKET: 164,
    BREAKDOWN_BACK_BUTTON: 165,
    BREAKDOWN_CANCEL: 166,

    // MAIN_FRONT_DOOR: 165,
    MAIN_FRONT_DOOR_SELECT_CV: 167,
    MAIN_FRONT_DOOR_CANCEL: 168,
    MAIN_FRONT_DOOR_CONFIRM: 169,
    MAIN_FRONT_DOOR_TERMINATE: 170,

    // MAIN_REDEEM: 170,
    MAIN_REDEEM_SUBMIT: 171,
    MAIN_REDEEM_CANCEL: 172,

    // PRINT ERROR
    COMMON_PRINT_ERROR: 175,

    MAIN_CASH_SINGLE_SUBMIT: 251,
    MAIN_CASH_MULTI_SUBMIT: 252,
    MAIN_CASH_MULTI_CONFIRM: 253,
    MAIN_CASH_MULTI_BACK: 254,
    MAIN_CASH_MULTI_CANCEL: 255,
    MAIN_CASH_INSPECTOR_TICKET: 256,
    MAIN_CASH_FARE_BOX: 257,
    MAIN_CASH_FARE_CALCULATION_BUS_STOP: 258,
    MAIN_CASH_FARE_CALCULATION_SUBMIT_BUS_STOP_CHANGE: 259,
    MAIN_CASH_FARE_CALCULATION: 260,
    MAIN_CASH_FARE_CALCULATION_PRINT: 261,
    MAIN_CASH_FARE_CALCULATION_BACK: 262,
    MAIN_CASH_TERMINATE: 263,

    MAIN_CJB_PLATE_NUMBER: 268,
    MAIN_CJB_PLATE_NUMBER_SUBMIT: 269,

    MAIN_FARE_BUS_STOP_MODE: 271,
    MAIN_FARE_BUS_STOP_SUBMIT: 272,

    MAIN_BLS_RECOVERED: 273,

    MAIN_BYPASS_TEN_BUS_STOP: 275,
    MAIN_FMS_BLS_ARE_NOT_WORKING: 277,

    MAIN_CHECK_POINT: 294,
    MAIN_CHECK_POINT_CLOSE: 297,

    CURRENT_SERVICE_INFO: 305,

    DATE_TIME_SETTING: 295,
    DATE_TIME_SUBMIT: 296,

    NEW_DAGW_OPERATION: 298,
    NEW_DAGW_OPERATION_CANCEL: 299,

    LOCK_CONFIRM: 144,
    NOTIFY_TO_LOCK: 145,
    UNLOCK_SUBMIT: 146,
    UNLOCK_SUCCESS: 35,

    CV_UPGRADE: 147,
    IGNITION_OFF: 148,
    BUS_OFF_ROUTE: 149,
    AUTO_DISABLE_BLS: 152,
    AUTO_DISABLE_BLS_CONFIRM: 153,
    INVALID_INSPECTOR_CARD: 154,

    //maintenance
    MAINTENANCE_APP_UPGRADE: 48,
    MAINTENANCE_UPGRADE_SUBMIT: 49,
    MAINTENANCE_PARAMETER: 50,
    MAINTENANCE_FMS: 57,
    MAINTENANCE_FARE_CONSOLE: 80, // use the same msg with main tab
    MAINTENANCE_DECK_TYPE_LIST: 81, // use the same msg with main tab
    MAINTENANCE_DECK_TYPE_SUBMIT: 82, // use the same msg with main tab
    MAINTENANCE_BLS_STATUS_SUBMIT: 83, // use the same msg with main tab
    MAINTENANCE_TIME_SUBMIT: 84, // use the same msg with main tab
    MAINTENANCE_DATE_SUBMIT: 85, // use the same msg with main tab
    MAINTENANCE_COMPLIMENTARY_DAYS_SUBMIT: 86, // use the same msg with main tab
    MAINTENANCE_DELETE_PARAMETER: 87, // use the same msg with main tab
    MAINTENANCE_FARE_CONSOLE_SUBMIT: 88, // use the same msg with main tab
    MAINTENANCE_DELETE_PARAMETER_NOTIFY: 89, // use the same msg with main tab

    MAINTENANCE_VERSION_INFO: 59,
    MAINTENANCE_BLS_INFORMATION: 61,
    MAINTENANCE_REDETECT_CV: 63,
    MAINTENANCE_LOAD_PARAMETERS: 64,
    MAINTENANCE_SAVE_TRANSACTION: 65,
    MAINTENANCE_AUDIT_REGISTRATION: 66,
    MAINTENANCE_CALIBRATE_BLS_TYPE: 68,
    MAINTENANCE_CALIBRATE_BLS_MANUAL: 69,
    MAINTENANCE_CALIBRATE_BLS_MANUAL_INPUT: 70,
    MAINTENANCE_CALIBRATE_BLS_MANUAL_CONFIRM: 71,

    MAINTENANCE_CALIBRATE_BLS_CALIBRATION: 72,
    MAINTENANCE_CALIBRATE_BLS_CALIBRATION_START: 73,
    MAINTENANCE_CALIBRATE_BLS_CALIBRATION_STOP: 74,
    MAINTENANCE_CALIBRATE_BLS_CALIBRATION_SEND_CMD: 75,
    MAINTENANCE_CALIBRATE_BLS_CALIBRATION_DISTANCE: 76,
    MAINTENANCE_CALIBRATE_BLS_CALIBRATION_RESULT: 77,

    MAINTENANCE_BUS_ID: 90, // use the same msg with main tab
    MAINTENANCE_OPERATOR: 91, // use the same msg with main tab
    MAINTENANCE_BUS_ID_SUBMIT: 92, // use the same msg with main tab

    MAINTENANCE_RESULT_NOTIFICATION: 93,
    MAINTENANCE_TEST_PRINT: 94,

    MAINTENANCE_BUS_ID_CHANGE: 95,
    MAINTENANCE_OPERATOR_CHANGE: 96,
    MAINTENANCE_SPID_CHANGE: 97,
    MAINTENANCE_SCREEN: 290,

    //fare
    FARE_SCREEN: 200,
    FARE_MENU_BUTTON: 180,
    FARE_BACK_BUTTON: 204,
    FARE_TC_DATETIME: 280,
    FARE_BYPASS_BLACKLIST_ACTIVE: 281,
    FARE_BYPASS_BLACKLIST_INACTIVE: 282,
    FARE_SPID: 283,

    // FARE SCREEN
    FARE_CANCEL_RIDE_CV1: 600,
    FARE_CANCEL_RIDE_CV2: 601,
    FARE_TRANSACTION: 602,
    FARE_PRINT_CASH_FARE: 603,
    FARE_CONCESSION_CV1: 604,
    FARE_CONCESSION_CV2: 605,
    FARE_TOP_UP: 606,
    FARE_CV_OPERATION: 607,
    FARE_BUS_STOP_MODE: 608,
    FARE_PRINTER_OPERATION: 609,
    FARE_EXTERNAL_DEVICES: 610,

    // FARE_CANCEL_RIDE_CV1: 181,
    FARE_CANCEL_RIDE_CANCEL: 182,
    FARE_CANCEL_RIDE_SUBMIT: 183,
    FARE_CANCEL_RIDE_CANCEL2: 184,
    FARE_CANCEL_RIDE_SUBMIT_NOTIFY: 185,

    // FARE_CONCESSION_CV1: 191,
    FARE_CONCESSION_CANCEL: 192,
    FARE_CONCESSION_SUBMIT: 193,
    FARE_CONCESSION_CANCEL2: 194,
    FARE_CONCESSION_SUBMIT_NOTIFY: 195,
    // FARE_CONCESSION_CV2_CANCEL: 196,
    // FARE_CONCESSION_CV2_SUBMIT: 197,
    // FARE_CONCESSION_CV2_CANCEL2: 198,

    FARE_TOP_UP_SELECT_AMT: 209,
    FARE_TOP_UP_SUBMIT: 210,

    FARE_BUS_STOP_MODE_SELECT: 211,
    FARE_BUS_STOP_MODE_SUBMIT: 212,

    FARE_TRANSACTION_SELECT: 201,
    FARE_TRANSACTION_CONFIRM: 203,
    FARE_TRANSACTION_BACK: 205,
    FARE_TRANSACTION_TERMINATE: 206,
    FARE_TRANSACTION_INFORMATION_TYPE_1: 207,
    FARE_TRANSACTION_INFORMATION_TYPE_2: 208,

    // CV Operation
    FARE_CV_OPERATION_BUTTON: 120,
    FARE_CV_OPERATION_BACK: 129,
    // CV OPERATION SCREEN
    FARE_CO_CV_STATUS: 621,
    FARE_CO_CV_ENTRY_EXIT: 622,
    FARE_CO_CV_MODE_CONTROL: 623,
    FARE_CO_POWER_ALL_CV_ON: 624,
    FARE_CO_POWER_ALL_CV_OFF: 625,
    FARE_CO_CV_POWER_CTRL: 626,
    FARE_CO_RESET_ALL_CV: 627,

    FARE_CO_CV_ENTRY_EXIT_CONFIRM: 121,
    FARE_CO_CV_ENTRY_EXIT_CANCEL: 122,
    FARE_CO_POWER_ALL_CV_CANCEL: 124,
    FARE_CO_POWER_ALL_CV_CONFIRM: 125,
    FARE_CO_CV_POWER_CTRL_CHANGE: 126,
    FARE_CO_RESET_ALL_CV_CANCEL: 127,
    FARE_CO_RESET_ALL_CV_CONFIRM: 128,
    FARE_CO_CV_MODE_CONTROL_SELECT: 123,
    FARE_CO_CV_MODE_CONTROL_CONFIRM: 131,

    // PRINTER OPERATIONS
    FARE_PRINT_OPERATION_BUTTON: 130,
    // FARE_PRINT_OPERATION_SCREEN
    FARE_PO_PRINT_RETENTION_TICKET: 611,
    FARE_PO_PRINTER_STATUS: 612,
    FARE_PO_PRINTER_ON: 613,
    FARE_PO_PRINTER_OFF: 614,

    FARE_PO_PRINT_RTK_SELECT: 133,
    FARE_PO_PRINT_RTK_CONFIRM: 134,
    FARE_PO_PRINT_RTK_TERMINATE: 135,
    FARE_PO_PRINT_RTK_CANCEL: 136,
    FARE_PO_PRINT_RTK_PRINT: 137,
    FARE_PO_PRINT_RTK_BACK: 138,

    // All tabs
    TRIGGER_FMS_STATUS: 43,
    CHANGE_FMS_STATUS: 44,
    TRIGGER_CRP_STATUS: 45,
    CHANGE_CRP_STATUS: 46,
    TRIGGER_BTS_STATUS: 51,
    CHANGE_BTS_STATUS: 52,
    RECONNECTION: 300,
    TC_DETECT_ERROR: 285,

    AUDIO_VOLUME_REQUEST: 292,
    AUDIO_VOLUME_NOTIFY: 293,

    DRIVER_STATUS: 301,
    ACKNOWLEDGE_DRIVER_STATUS: 302,

    LOCATION_CONFIG_STATUS: 303,
    POSN_SOURCE: 304,

    TAP_CARD_NOTIFICATION: 306,
    LOGIN_ROLE_SUBMIT: 307,
    MAINTENANCE_BACK: 308,
    LOGIN_OPTION_ERROR: 309,

    VALIDATE_MESSAGE_FORMAT: 310,

    LOGIN_BACK: 311,
    HASH_PASSWORD: 312,
    HASH_PASSWORD_RESULT: 313,

    // broadcast
    LANGUAGE_SETTING: 7777, // only privately use in MADT
    VOLUME_SETTING: 8888, // only privately use in MADT
    // LOGIN_SUCCESS: 8888, // only privately use in MADT
    // LOGOUT_SUCCESS: 9999, // only privately use in MADT
    // START_TRIP_SUCCESS: 10000, // only privately use in MADT
    // END_TRIP_SUCCESS: 10001, // only privately use in MADT
    // LOCK_BROAD_CAST: 10002, // only privately use in MADT
    // UNLOCK_BROAD_CAST: 10003, // only privately use in MADT
} as const;

export const CVLabels = {
    1: 'Workfare',
    2: 'PWD',
    3: 'NSF',
    4: 'Student',
    5: 'Senior',
    6: 'Children',
    7: 'Staff',
    8: 'Monthly Adult',
    9: '',
    10: 'Ride Cancelled',
} as const;

export const DagwOperationStatus = {
    NA: 0,
    SUCCESS: 1,
    FAILURE: 2,
} as const;

export const ResponseStatus = {
    SUCCESS: 1,
    PROGRESS: 2,
    ERROR: 3,
    NA: 4,
} as const;

export const MsgSubID = {
    REQUEST: 1, // Request information
    RESPONSE: 2, // Response The Message ID should be same as the request Message ID
    NOTIFY: 3, //Notify Update information. No response is required.
} as const;

export const CvTypes = {
    CV1: 'CV1',
    CV2: 'CV2',
} as const;

export const PageType = {
    CANCEL: 'cancel',
    CONCESSION: 'concession',
} as const;
// removes this once done upgrading to new message format
export const MessageId = {
    VEHICLE_JOURNEY: 'vehicle-journey',
    VEHICLE_STATE: 'vehicle-state',
    HEADWAY_TIME_TABLE: 'headway-time-table',
    NEXT_BUS_INFO: 'next-bus-info',
    CV_ICON_TAP_CARD: 'cv-icon-tap-card',
    CV_AVAIL_STATUS: 'cv-avail-status',
    AUTH: 'auth-status',
    SHUTTING_DOWN: 'shutting-down',
    GET_MAIN_TAB_DATA: 'get-main-tab-data',
    SEND_FARE_BUS_STOP: 'send-fare-bus-stop',
    CONNECTION_STATUS: 'connection-status',
} as const;

export const AuthStatus = {
    LOGGED_IN: 'logged-in',
    BOOT_UP: 'boot-up',
    SIGN_IN: 'sign-in',
    OUT_OF_SERVICE_INFO: 'out-of-service-info',
    OUT_OF_SERVICE_MISSING_DATA: 'out-of-service-missing-data',
    SELECT_LANGUAGE: 'select-language',
    FARE_CONSOLE_SETTING: 'fare-console-setting',
    SIGN_IN_TAP_CARD: 'sign-in-tap-card',
    SIGN_IN_MANUAL: 'sign-in-manual',
    BUS_OPERATION_MENU: 'bus-operation-menu',
};

export const HTTimeColor = {
    green: '0x019646',
    blue: '0x0F65A1',
    orange: '0xC25500',
    black: '0x000000',
} as const;

export const OutOfServiceType = {
    WITH_INFO: 'with_info', // REMOVE THIS WHEN DONE UPDATING TO THE NEW FORMAT
    NO_DATA: 'no_data', // REMOVE THIS WHEN DONE UPDATING TO THE NEW FORMAT
    MISSING_DATA: 'MISSING_DATA',
    PENDING_UPGRADE_CV: 'OUT_OF_SERVICE_PENDING_UPGRADE_CV',
    PENDING_UPGRADE_READER: 'OUT_OF_SERVICE_PENDING_UPGRADE_READER',
    PENDING_UPGRADE_CV_READER: 'OUT_OF_SERVICE_PENDING_UPGRADE_CV_READER',
} as const;

export const TopicsKeys = {
    COMMISSIONING_DIGIT_KEY_IN: 'COMMISSIONING_DIGIT_KEY_IN',
    START_TRIP: 'START_TRIP',
    MAINTENANCE: 'MAINTENANCE',
    MAIN_TAB: 'MAIN_TAB',
    MAIN_TAB_CV: 'MAIN_TAB_CV',
    MAIN_TAB_FARE_BUS_STOP_LIST: 'MAIN_TAB_FARE_BUS_STOP_LIST',
    MAIN_TAB_FARE_BUS_STOP: 'MAIN_TAB_FARE_BUS_STOP',
    MAIN_TAB_FMS_BUS_STOP: 'MAIN_TAB_FMS_BUS_STOP',
    MAIN_HEADWAY_TIME_TABLE: 'MAIN_HEADWAY_TIME_TABLE',
    CURRENT_SERVICE_INFO: 'CURRENT_SERVICE_INFO',
    FARE_TAB: 'FARE_TAB',
    ALL_TAB: 'ALL_TAB',
    MAINTENANCE_FARE: 'MAINTENANCE_FARE',
    FMS_STATUS: 'FMS_STATUS',
    BOLC_STATUS: 'BOLC_STATUS',
    BTS_STATUS: 'BTS_STATUS',
    CRP_STATUS: 'CRP_STATUS',
    POSN_STATUS: 'POSN_STATUS',
    LOCATION_CONFIG_STATUS: 'CONFIG_STATUS',
};

export const CvStatusType = {
    NO_TAPPING: 1,
    DISCONNECTED: 2,
    ENTRY: 3,
    ENTRY_EXIT: 4,
    EXIT: 5,
    FREE: 6,
    NA: 7,
} as const;

export const CvDirTypeArray = Object.entries(CvStatusType).map(([key, value]) => ({ key, value }));

export enum StartTripTypes {
    FMS_NO_INFO = 'FMS_NO_INFO',
    FMS_VALID_INFO = 'FMS_VALID_INFO',
    FMS_TRIP_INFO_MISMATCH = 'FMS_TRIP_INFO_MISMATCH',
    FMS_BUS_STOP_MISMATCH = 'FMS_BUS_STOP_MISMATCH',
}

export const MessageKeys = {
    FARE_TRIP_DETAILS_SUCCESS: 'FARE_TRIP_DETAILS_SUCCESS',
};

// export const TripDetailsType = {
//     FMS_NO_INFO: 'FMS_NO_INFO',
//     FMS_VALID_INFO: 'FMS_VALID_INFO',
//     FMS_TRIP_INFO_MISMATCH: 'FMS_TRIP_INFO_MISMATCH',
//     FMS_BUS_STOP_MISMATCH: 'FMS_BUS_STOP_MISMATCH',
// };

export const CommissioningType = {
    IN_PROGRESS: 'COMMISSIONING_IN_PROGRESS',
    CLEARING_ALL_DATA: 'COMMISSIONING_CLEARING_ALL_DATA',
    COMPLETED_CLEANING: 'COMMISSIONING_COMPLETED_CLEANING',
};

export const FareCVStatus = {
    1: 'CV_IN_SERVICE',
    2: 'CV_OUT_OF_SERVICE',
    3: 'CV_LOGIN',
    4: 'CV_BROKEN',
    5: 'CV_PWR_OFF',
    6: 'CV_BUSY',
    7: 'CV_NOT_INSTALLED',
    8: 'CV_NO_COMMS',
} as const;

export const FareCVSubStatus = {
    0: '',
    1: 'CV_INVALID',
    2: 'CV_ENTRY',
    3: 'CV_EXIT',
    4: 'CV_AUTO',
    5: 'CV_ENQUIRY',
    6: 'CV_CANCEL_RIDE',
    7: 'CV_FRONT_EXIT',
    8: 'CV_CHKPT_EXIT',
    9: 'CV_CHKPT_ENTRY',
    10: 'CV_MAX_PENALTY',
    11: 'CV_MIN_PENALTY',
} as const;

export enum MainPagePopUp {
    BUS_STOP_MISMATCH = 'FMS_BUS_STOP_MISMATCH',
    TRIP_MISMATCH = 'FMS_TRIP_INFO_MISMATCH',
    DRIVER_ID_CHANGES = 'DRIVER_ID_CHANGES',
    DRIVER_BLOCKED_LOG_OFF = 'DRIVER_BLOCKED_LOG_OFF',
    FMS_NO_INFO = 'FMS_NO_INFO',
}

// export const MainPagePopUpList = [
//     MainPagePopUp?.BUS_STOP_MISMATCH,
//     MainPagePopUp?.TRIP_MISMATCH,
//     MainPagePopUp?.DRIVER_ID_CHANGES,
//     MainPagePopUp?.DRIVER_BLOCKED_LOG_OFF,
//     MainPagePopUp?.FMS_NO_INFO,
// ];

export const DEFAULT_TIMEOUT = 5000;
export const DEFAULT_NOTIFICATION_TIMEOUT = 3000;

export const LocalStorageKey = {
    AUTH: 'auth',
    IS_ON_TRIP: 'isOnTrip',
    DEVICE_STATUS: 'deviceStatus',
    LANGUAGE: 'lang',
    VOLUME: 'volume',
    STATUS_FMS: 'statusFMS',
    STATUS_BOLC: 'statusBOLC',
    STATUS_BTS: 'statusBTS',
    STATUS_CRP: 'statusCRP',
};

export const MainScreen = {
    MAIN_SCREEN: 1,
    ACCESS_DENIED: 2,
};

export const FareScreen = {
    LOGIN_FROM_MAIN_TAB: 1,
    WAITING_TRIP_TO_START: 2,
    ON_TRIP_LANDING_PAGE: 3,
    ACCESS_DENIED: 4,
};

export const MaintenanceScreen = {
    LOGIN_FROM_MAIN_TAB: 1,
    LANDING_PAGE: 2,
    ACCESS_DENIED: 3,
};
